### ISSUE TITLE
JavaScript refresher + Typescript

### ISSUE THREAD

**Issue by hungnp194** [zinza-d2-training/haivh-react#1]
- JavaScript refresher
  - https://github.com/zinza-d2-training/new-to-react/blob/fresher/01_Day_JavaScript_Refresher/01_javascript_refresher.md

- Tìm hiểu về Typescript
  - [Spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) 
  - [Destructing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
  - [Object reference and cloning](https://javascript.info/object-copy)
  - [Default Types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html)
  - [Interface/Type](https://www.typescriptlang.org/docs/handbook/2/objects.html)
  - [Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html)
  - [Class](https://www.typescriptlang.org/docs/handbook/2/classes.html)
  - Function type, arrow Func
  - [Advanced Type](https://www.typescriptlang.org/docs/handbook/utility-types.html)

- Bài tập
  - Clone object đã cho, sử dụng spread và destructing. Yêu cầu object và thuộc tính của object đã cloned không có reference tới object cũ [Link](https://codesandbox.io/s/spread-operator-destructing-object-cloning-rjmcy?file=/src/index.js)
  - Viết Model type cho các table database 

![covidtracker](https://user-images.githubusercontent.com/61738572/150733206-6ca87af2-86f0-464e-94b3-ef651c925930.png)

  - Sử dụng các advanced type để viết interface Scalars đại diện cho các kiểu dữ liệu của DB (Ví dụ: Int => number, varchar => string)
  - Sử dụng Scalars để thay thế các type cho model ở trên. Viết các type InsertInput (create api), SetInput (update api) kế thừa từ các model trên. (Ví dụ VaccineInsertInput, VaccineSetInput)

  - Mẫu đã làm [Link](https://www.typescriptlang.org/play#code/C4TwDgpgBAsghiARhAPAFQHxQLxTVAHygDsBXAG3IG4AoGgS2OAgCcAzOAY2gGVO5ycFgGcoAbxpQpUAJJMAXCVIBbZCwA0k6WkYhGwRWVWtN0qABEA9qUTkIhlWtPSAYuUtwDS4xq1SdyhDCwHDKYIrBLIwA5s5S5p4QwPSBEcBRxNF+eBAAHl6RMXFQAGpCnAAWQmkZsdkJzDVF2QH2UIWZNAC+dPqsHNx4KUEhYS70EOQAJqISZpwsEIlTAPqeinwCQsIA2gDkrcGhYHsAusWkYFPLa16bgiL7h6Mn5929TP1c0ADCi8sAVWErHGkxm4myCyWzFWiBAAH5FPAkKh7tt9nJgGcMMUoTc4StSMCWIjYAhkCggawce8GJ92N8oAAhODA0HTUR5ZjEcHPY7smbqKB-aEQKZUlgC2Y9OnMBmDMqcTiMaBciA80QstkTDkQsz0KYbfgPXZ7TFnYrEUJtNGPPZlFiVIQW7JwUjACqWKIALzFRq2dp0xD0TBdZjYLEsyjW0RtxvRZtDbzMwEsMYgpORFNtpvNpxpZmEnuAwn9JoxSeKRcsJZWU3oR2I3Ez5NR8bteYL0jYFHIIBWADcuMqrTCywm85oZaBIKVhyq5MTgHIwO6cFAAAr0TgAaxQipHECFewNe0IUD2VsCZ6IezdHq99F9UxvF4jUfTr72qc-5721ZLL8AOEOsGxCJsIC-HtKH7IclUYZY9gwWgZ2gA8VR4JIVzXXANyEZIBEpYlF1YZdiFXYAMA+OUBl+awmBYEAoDVDVmVZCApT1aQDXHDtK2yK84wDU0HSdFgw2kOCR08ehLGIUs53g0dZOIHZTlpVDhXo9IQBIlgyIo9ct13FAfm0xjj1PP9BKQlDwDo0gGJATCDJwzd8PoQizMcnS9NcyjqK+BV52UuTmPydVwS1DidXBOZuMNKAcwrLFk2kThzP7HikvbXN+LMKSELHHLhJSiSpGgvtBxC5ZeLy1LcUyxRvKcqc6E09DQuIPzsOAIztz3TqZLkyyXz-DKfMYlYrNvQrRzFKDe1gmqYVsmgOpWlSXN6oyPMIobkjknryPdKjZSC352PC7kovYzj4qkbLksTBrsmuRoSvLA5hiOMJyqgCanOmxLnsnSF2IU0H8ukKZoQqSHcrKtKpEBnTmsytr1vs4V2OOwzcIG0z2NGr93sg8bMuBr9+GBYRSbhunkKx2cfnY7aTr63C9vIIngTx07AvlaAJWuyLNTu2LZmyJ7EZe-62HoERgBWQS6v2USqnE5GoEEYIVetNX7XKTX-ogZQ4HochDY151tbAVlhAAdy9EHZZtrXMc0iV+c5zdCYlEm-wVpX9evP9deVmy-zNi3yC-e3hCdl21q94l2fx9z9M8nnvfk0jeqoqQgA)

**Comment by haivu2912** [comment]
1. Javascript refresher

- Các cách thêm js vào 1 trang web: inline, internal, external
- Biến trong js: var, let, const

- Kiểu dữ liệu trong js: 
+ Kiểu dữ liệu nguyên thủy: number, string, boolean, null, undefind, symbol
+ Kiểu dữ liệu không nguyên thủy: array, object

- Mảng và một số phưởng thức của mảng như:
+ split: cắt một chuỗi thành một mảng
+ fill: gán tất cả các phần tử của mảng bằng một giá trị tĩnh
+ concat: nối mảng
+ length: lấy độ dài của mảng
+ indexOf: kiểm tra vị trí của một phần tử trong mảng, nếu tìm thấy trả về vị trí của phần tử đó, nếu không trả về -1
+ lastInexOf: trả về vị trí cuối cùng của một phần tử trong mảng, nếu có trả về vị trí cuối cùngcủa phần tử đó, nếu không trả về -1
+ toString: chuyển mảng thành chuỗi
+ join: nối các phần tử của mảng
+ slice: cắt các phần tử trong 1 phạm vi
+ splice: xóa và thay thế phần tử
+ push: thêm một phần tử vào cuối mảng
+ pop: xóa một phần tử cuối mảng
+ shift: xóa một phần tử đầu mảng
+ unshift: thêm một phần tử vào đầu mảng
+ reverse: đảo ngược mảng
+ sort: sắp xếp các phần tử của mang

- Các điều kiện như: if, if else, if else if else, switch case, toán tử ba ngôi
- Vòng lặp: for, while, do while, for of, for each, for in
- Phạm vi: window, toàn cục, cục bộ
- Object và các phương thức của object:
+ assign: copy một object mà không thay đổi object gốc
+ key: lấy một mảng các key của object
+ entries: lấy một mảng key và value của object
+ hasOwnProperty: kiểm tra một key có tồn tại trong object hay không

- Hàm: declaration function, expression function, anonymous function, arrow fuction
- HOF: là một hàm nhận một hàm khác làm tham số hoặc trả về một function

- Phân biệt rest và spread: 
+ rest được sử dụng trong destructuring hoặc làm tham số của một hàm
+ spread được sử dụng làm đối số của một hàm hoặc để rải vào một array hoặc object khác

- Xem lại mộ số hàm như forEach, map, filter, find, reduce, some, every

2. Tìm hiểu về Typescript

- Type trong ts:
+ string, number, boolean giống trong js
+ any: một kiểu dữ liệu đặc biệt trong ts có thể nhận bất kì giá trị nào
+ object type: có thể chỉ định các thuộc tính thành optional bằng cách thêm ?, chỉ định các thuộc tính thành chỉ đọc bằng readonly
+ union type:  kiểu dữ liệu kết hợp, giá trị có thể nhận các kiểu dữ liệu đã khai báo
+ type alias: tạo ra một kiểu dữ liệu có thể được sử dụng nhiều lần bằng tên đã định nghĩa
+ interface: giống với type alias nhưng interface có thể chỉnh sửa được sau khi đã định nghĩa còn type alias thì không
+ type assertion: giúp nhận các giá trị của của DOM

- Có thể kế thừa bằng cách sử dụng từ khóa extend hoặc & 
- Một số advance type:
+ partial<Type>: biến các thuộc tình thành tùy chọn 
+ require<Type>: đặt các thuộc tình thành bắt buộc phải có
+ readonly<Type>: đặt các thuộc tình sang chế độ chỉ có thể đọc
+ record<Keys, Type>: lấy key từ  Key và value có kiểu dữ liệu từ Type, dùng để ánh xạ từ các type khẫ
+ pick<Type, Keys>: tạo key bằng string literal hoặc union of string literals và kiểu dữ liệu từ Type
+ omit<Type, Keys>: lấy các thuộc tính của Type và xóa key được khai báo ở Key
+ exclude<UnionType, ExcludedMembers>: tạo một union type mà xóa union member được khai báo ở ExcludedMembers
+ extract<Type, Union>: tạo một kiểu mà type của nó có ở union
+ nonNullable<Type>: xóa null và undefind ở type
+ parameters<Type>: tạo một type mà nó có type là tham số của function Type
+ returnType<Type>: tạo một type mà nó có type là giá trị trả về của function Type

3.  Bài tập

- [Bài 1]( https://codesandbox.io/s/spread-operator-destructing-object-cloning-forked-9r66fy?file=/src/index.js)
- [ Bài 2](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoLgGzlAzsgbwChlTkBJAOQBUAuZEAVwFsAjaAGhLOqoE0qdBi3ZQuZZLwCyAUVTUAglIAK9Jm07dSANQUAlAMIAJffVxgooAOZcAvkSKhIsRCmAATQluQf66LDi4ANoA5IIhALpE9o7g0PBIyGDAzCjEEghQEHCQ7gD6OX4Y2Hih0nKKKpHiZIwADu45EAVgRQGlIeXySsrV0Q5O8a7ImdmQAEIAnl4ZWU35rJNtJcFhNJH9sc4JKKxwuCgQAB6QIO74HhxJKRBXo01TXpuDLokAbogIoBD4x6fnyD2BxmZBAcFSy0CoV0hhMej6EjgjDAAAsAPaWABeEHckI6vEoAnWERqpBgUDRzAKVggeNW4RJ3jAaOptLQxSha2oCLIuHRYFwdNCDNJyD5aLAeXcwHMcBASCFXJ5ZMYmEwkzyHwQXzBuUVIs2YEmdRQWp1P3IIAOUDAlrqyOQAF5kMpgAgANYAHjN31wVxCYNSIWQAB9kCEkaiMcBse5g2GQuTKaz4+HmSnQ+HxQLUyFs1KZWA5UhczBVerNZ9QPNgwA+IhGk3IH0gH6oCC2kDKB3O5Q4ZJYb1V1u4etbIaJRjW34nCBnfBAtLeGDAPCSwNs-wraH6Yz6ZXIbDmPIbxUwvfwxkSCDMODATBn3dwg91fa4ADuGNx7Paq3Pz6iGJGxQKdoFwS1rU7e0wCdF03S9UC8H9Fc1xPcEIFzI913Q3MbzvTBc1fXAPy-EJ62A5BENwdswBAaDYL7G1gEHKixxeHYRn2H5kD+OcAUXEFSAQNFGHAKANV8H9tyVKIMi4wUpM5A0JHcMYUQUrclOJQ1jRQDADnAq1oCgns4I9T19J+f1hNEiwJLjTMQks3Bc1UnJ1LIhtdM4gyaLtUzGIHTALPkti4lePSRLE4BuN4+dAS4wSGHQx9YX3QCHAomyxMmCDjP8mDe3giyoosGK-XDDdPKy0rxL8uiAv7ZjguysqfjC7ZhhbHJgDRK0eNneKBPSMhWvEvJJM0jplLIbq9UU6biVFMs1Q1OacX1bSgO8ubeqtPKbQKhjit2vqKqc2r7NzdaHITFaKxu6qduHHqzvq+jeyawdTqtWsgA)
